name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ci-app:
  #   name: CI app
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get repository code
  #       uses: actions/checkout@v4
  #     - name: Set up pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 9
  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile
  #     - name: Type checking
  #       run: pnpm tsc
  #     - name: Linting
  #       run: pnpm lint

  cd-app:
    name: CD app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 905192326261.dkr.ecr.eu-central-1.amazonaws.com
      - name: Build Docker image
        run: |
          docker build -t image-loader .
      - name: Tag image
        run: |
          docker tag image-loader:latest 905192326261.dkr.ecr.eu-central-1.amazonaws.com/image-loader:latest

      - name: Push image
        run: |
          docker push 905192326261.dkr.ecr.eu-central-1.amazonaws.com/image-loader:latest

      - name: Deploy
        run: |
          aws ecs update-service --cluster image-loader-cluster-2-4r2jo7 --service image-loader-service-ujv99t2h --force-new-deployment
